### ISSUE TITLE
Which version of the GPL is this licensed under?

### ISSUE THREAD

**Issue by adamvoss** [JoaoDiogoFalcao/Arduino_Due_SD_HSCMI#1]
According to **Arduino_Due_SD_HSCMI.h** [this is licensed under the GPL](https://github.com/JoaoDiogoFalcao/Arduino_Due_SD_HSCMI/blob/afc561732a0a52cc22e3e1ab4b4ab69b752939e8/Arduino_Due_SD_HSCMI.h#L11).  Is that v2 or v3?  Is there an or later clause?

**Comment by JoaoDiogoFalcao** [comment]
Just added a LICENSE file it is under MIT license...

**Comment by adamvoss** [comment]
Thanks!  MIT definitely works better for where I was seeing this used.

I do see [this in the header](https://github.com/JoaoDiogoFalcao/Arduino_Due_SD_HSCMI/blob/485f8339ef94b72abded52f8154f2c74ab74c0bf/Arduino_Due_SD_HSCMI.h#L4-L5):

> Adapted from:
>    RepRapFirmware - Platform: RepRapPro Ormerod with Duet controller

RepRapFirmware is GPL licensed.  I assume you are not a lawyer and probably can't give legal advice, but to confirm, you believe the influence from RepRapFirmware was little enough to not count as a derivative (and therefore avoid needing to be GPL licensed)?

**Comment by JoaoDiogoFalcao** [comment]
I found it on RepRap but the actual HSCMI part is not originally from their repo. Further their GPL license is targeted at their Hardware design. You can actually find the SD_HSCMI in other repos that use MIT License.

**Comment by adamvoss** [comment]
I did some spelunking through RepRap history to assure myself.  I had seen the SD_HSCMI parts were under there own licenses (some of which at least are technically not even GPL-compatible).

Unless I missed something, Arduino_Due_SD_HSCMI.(cpp|h) is your original work.  It appears the only file that may be under RepRapFirmware's GPL license is SD_HSMCI.h.  Even if it is, it is a fairly minimal header file so I think it can probably be justified (either as fair use or otherwise) that your files do not need to be GPL by association.

Thanks for relicensing!

**Comment by JoaoDiogoFalcao** [comment]
I believe SD_HSCMI.h is originally from the Atmel's Library.
