### ISSUE TITLE
Was the letter transposition intentional?

### ISSUE THREAD

**Issue by adamvoss** [JoaoDiogoFalcao/Arduino_Due_SD_HSCMI#3]
This library consistently uses "HSCMI"  instead of "HSMCI" (High Speed MultiMedia Card Interface).  Was this a typo that propagated or an intentional name choice?

**Comment by JoaoDiogoFalcao** [comment]
Typo... :(

**Comment by adamvoss** [comment]
Any interest in a PR that corrects these, or do you prefer not to since it is already in the wild?

**Comment by adamvoss** [comment]
Resolved by #6.
